-- Augur Taxonomy Database Schema
-- Generated by build_taxonomy_db.py
--

CREATE TABLE cascade_chain_signals (
            cascade_id INTEGER REFERENCES cascade_chains(id),
            signal_id INTEGER REFERENCES signals(id),
            sequence_order INTEGER NOT NULL,
            PRIMARY KEY (cascade_id, signal_id)
        );

CREATE TABLE cascade_chains (
            id INTEGER PRIMARY KEY,
            chain_name TEXT NOT NULL,
            description TEXT,
            trigger_sector_id INTEGER REFERENCES sectors(id),
            estimated_propagation_time TEXT
        );

CREATE TABLE cross_sector_links (
            id INTEGER PRIMARY KEY,
            source_signal_id INTEGER REFERENCES signals(id),
            target_signal_id INTEGER REFERENCES signals(id),
            relationship_type TEXT,
            strength REAL,
            notes TEXT
        );

CREATE TABLE data_sources (
            id INTEGER PRIMARY KEY,
            source_name TEXT NOT NULL,
            source_type TEXT,
            url TEXT,
            access_type TEXT CHECK(access_type IN ('Free','Gated','Paid','Enterprise')),
            update_frequency TEXT
        );

CREATE TABLE sectors (
            id INTEGER PRIMARY KEY,
            name TEXT UNIQUE NOT NULL,
            gics_code TEXT,
            description TEXT
        );

CREATE TABLE signal_data_sources (
            signal_id INTEGER REFERENCES signals(id),
            source_id INTEGER REFERENCES data_sources(id),
            PRIMARY KEY (signal_id, source_id)
        );

CREATE TABLE signal_subsectors (
            signal_id INTEGER REFERENCES signals(id),
            subsector_id INTEGER REFERENCES subsectors(id),
            PRIMARY KEY (signal_id, subsector_id)
        );

CREATE TABLE signals (
            id INTEGER PRIMARY KEY,
            sector_id INTEGER REFERENCES sectors(id),
            tier_id INTEGER REFERENCES tiers(id),
            signal_name TEXT NOT NULL,
            description TEXT,
            irreversibility_score REAL CHECK(irreversibility_score >= 0 AND irreversibility_score <= 1),
            lead_lag_type TEXT CHECK(lead_lag_type IN ('Leading','Coincident','Lagging','Leading/Coincident','Leading/Lagging','Coincident/Lagging','Lagging/Coincident')),
            lead_time_estimate TEXT,
            priority TEXT CHECK(priority IN ('P0','P1','P2','P3')),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

CREATE TABLE subsectors (
            id INTEGER PRIMARY KEY,
            sector_id INTEGER REFERENCES sectors(id),
            name TEXT NOT NULL,
            description TEXT
        );

CREATE TABLE tiers (
            id INTEGER PRIMARY KEY,
            tier_number INTEGER UNIQUE NOT NULL,
            name TEXT NOT NULL,
            description TEXT,
            avg_irreversibility REAL
        );

CREATE INDEX idx_signals_irreversibility ON signals(irreversibility_score DESC);

CREATE INDEX idx_signals_lead_lag ON signals(lead_lag_type, lead_time_estimate);

CREATE INDEX idx_signals_priority ON signals(priority);

CREATE INDEX idx_signals_sector ON signals(sector_id);

CREATE INDEX idx_signals_tier ON signals(tier_id);

CREATE VIEW v_cascade_chains AS
        SELECT cc.chain_name, cc.description, s.name AS trigger_sector,
               cc.estimated_propagation_time,
               GROUP_CONCAT(sig.signal_name, ' → ') AS signal_chain
        FROM cascade_chains cc
        LEFT JOIN sectors s ON cc.trigger_sector_id = s.id
        LEFT JOIN cascade_chain_signals ccs ON cc.id = ccs.cascade_id
        LEFT JOIN signals sig ON ccs.signal_id = sig.id
        GROUP BY cc.id;

CREATE VIEW v_highest_irreversibility AS
        SELECT sig.signal_name, s.name AS sector, t.tier_number,
               sig.irreversibility_score
        FROM signals sig
        JOIN sectors s ON sig.sector_id = s.id
        JOIN tiers t ON sig.tier_id = t.id
        WHERE sig.irreversibility_score IS NOT NULL
        ORDER BY sig.irreversibility_score DESC
        LIMIT 100;

CREATE VIEW v_priority_signals AS
        SELECT sig.signal_name, s.name AS sector, sig.priority,
               sig.irreversibility_score, sig.lead_lag_type
        FROM signals sig
        JOIN sectors s ON sig.sector_id = s.id
        WHERE sig.priority IN ('P0','P1')
        ORDER BY sig.priority, sig.irreversibility_score DESC;

CREATE VIEW v_signal_count_by_sector AS
        SELECT s.name AS sector, t.tier_number, t.name AS tier_name,
               COUNT(sig.id) AS signal_count
        FROM signals sig
        JOIN sectors s ON sig.sector_id = s.id
        JOIN tiers t ON sig.tier_id = t.id
        GROUP BY s.id, t.id
        ORDER BY s.name, t.tier_number;

CREATE VIEW v_top_leading_signals AS
        SELECT sig.signal_name, s.name AS sector, sig.lead_lag_type,
               sig.lead_time_estimate, sig.irreversibility_score
        FROM signals sig
        JOIN sectors s ON sig.sector_id = s.id
        WHERE sig.lead_lag_type LIKE 'Leading%'
        ORDER BY sig.lead_time_estimate ASC
        LIMIT 100;
